### ISSUE TITLE
WER on benchmark tables

### ISSUE THREAD

**Issue by asr-lord** [SYSTRAN/faster-whisper#1172]
It would be helpful if you could share the WER metrics as well on Benchmarks

https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#benchmark

**Comment by MahmoudAshraf97** [comment]
It's indeed, and it's also important IMO, but the problem is that I don't have the reference transcription to calculate the WER

**Comment by asr-lord** [comment]
I know this and the problem with using Common Voice, Gigaspeech or any other open label dataset is that they are not long form audio.

**Comment by MahmoudAshraf97** [comment]
I managed to obtain the transcript, unfortunately, it turned out that this exact audio is in the training data of whisper as the exact captions appeared in silence regions, so WER results will be misleading.
If you want to benchmark on longform audio use the YT Commons dataset that was used to benchmark the distil models
