### ISSUE TITLE
batched inference generating inaccurate segments

### ISSUE THREAD

**Issue by Saccarab** [SYSTRAN/faster-whisper#1175]
there seems to be significant difference between segment detection when using[ plain whisper](https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py#L523) vs [batched inference](https://github.com/SYSTRAN/faster-whisper/blob/master/faster_whisper/transcribe.py#L950)

batched seems to perform way worse on most of the files I've tested, is this a known side effect of batching? 
would it be possible to generate segments for the individual batches?

**Comment by MahmoudAshraf97** [comment]
what exactly do you mean by segment detection?

**Comment by Purfview** [comment]
I think he meant chunking.

Btw, I see difference in chunking the current vs [r194](https://github.com/SYSTRAN/faster-whisper/tree/46080e584e7a1066b42194b6c7954ad04acc7b03) is it because something changed in the padding?

**Comment by MahmoudAshraf97** [comment]
There were many subtle changes since that commit (VAD, features padding, different PyAV versions) that should not affect the transcription quality, although it might be difficult to reproduce something as chunking.
The encoder padding should not affect any usecase where `chunk_length` is 30s

**Comment by Saccarab** [comment]
**segments return with batched**
![image](https://github.com/user-attachments/assets/3269ffa3-bb2d-497e-bbe5-9b56be86e639)


**without batched**
![image](https://github.com/user-attachments/assets/2e1c5a55-0c38-4cc5-a455-20fe8fd2f3f0)

the returned segments for the same file when using the batched model seems to give way chunkier segments

**Comment by MahmoudAshraf97** [comment]
use `without_timestamps=False`, but the transcription quality may be worse and it will be slower

**Comment by Saccarab** [comment]
that did it, thanks for pointing me in right direction

**Comment by twmht** [comment]
@MahmoudAshraf97 

Why should we set without_timestamps=False to fix this, and why might the transcription quality be worse?

**Comment by MahmoudAshraf97** [comment]
First of all, this is not an issue so that we can fix it, this is an option that the user can control, `without_timestamps=False` generates approximate timestamp tokens that are used to split the transcription of a 30s window, this is not needed in batched transcription and hence turned off by default so that we don't generate unnecessary tokens, turning it on will lead to worse result due to a bug in CT2 https://github.com/OpenNMT/CTranslate2/issues/1783 or is it from the model itself, I haven't tested extensively

**Comment by Saccarab** [comment]
The quality decrease without_timestamps=True introduces, would that be more significant when using batched inference in comparison assuming we already were using without_timestamps=True previously?

**Comment by MahmoudAshraf97** [comment]
using `without_timestamps=True` previously produced even worse results because the longform transcription algorithm depends on the timestamps, that's why the degradation wasn't noticeable, but when we use an algorithm that did not depend on timestamps, we can objectively compare the results with and without the timestamps
