### ISSUE TITLE
can finetuned Whisper models use option "initial_prompt"?

### ISSUE THREAD

**Issue by v-yunbin** [SYSTRAN/faster-whisper#590]
Based on whisper-large-v2 model， I have finetuned a chinese Whisper on my own data with transformers .
convert it ctranslate2 model format, when use  option "initial_prompt", audio cannot be transcribed correctly  and  not use  option "initial_prompt", audio can be transcribed correctly. Any suggestions?

For ctranslate2 whisper-large-v2 model，using  option "initial_prompt" is normal.

**Comment by blackpolarz** [comment]
Did you convert your finetuned model using the latest ctranslate2 conversion script? There were a period of time (not too long ago where the conversion script is not working properly). The update has fixed it so it might be the same problem. 
If you do not mind sharing your own model, maybe some of us can try to convert the model on our end and see if we face the same issue?
Do also share with us what you have tried to prompt and your test audio if possible.
If the problem lies with "hallucinations" where whisper transcribes random stuff even when there is no audio or just music, you might want to set VAD to true as that will help hallucinations slightly.

**Comment by v-yunbin** [comment]
> ctranslate2

yes，I use ctranslate2==3.22.0,  sorry，Model cannot be shared due to company security policy.

I use latest ctranslate2 convert https://huggingface.co/openai/whisper-large-v2,  using option "initial_prompt" ,  test a chinese audio and it works.
but I use latest ctranslate2 convert my finetuned model,  using option "initial_prompt" get a Russian resulrt as "ampaampaampaampaampatitampa�" or empty result.

**Comment by blackpolarz** [comment]
1) Have you tried forcing the language parameter in the transcribe function to be chinese? 
This will force the model to recognise your transcription as Chinese wherever possible.
2) Have you tried extracting the language probability info for your finetuned model? 
I am suspecting that somehow during the first 30s which is used to determine the language of the audio, the probability of the Russian is somehow higher than Chinese. It is also very likely that the tokens have been modified during the finetuning. 
Just to check, does your model (based on whisper v2) transcribe properly when using the huggingface implementation? With and without initial prompt?

As the initial prompt only preprocesses and converts to tokens in faster-whisper and leaves all the backend computation in ctranslate2. We might need to look into the whisper implementation of ctranslate2. But it is still highly likely that the problem lies in the model rather than the backend.

**Comment by v-yunbin** [comment]
> 1. Have you tried forcing the language parameter in the transcribe function to be chinese?
   This will force the model to recognise your transcription as Chinese wherever possible.
    
    yes, my codes is as follows:
    ```
   model = WhisperModel(model_path, device="cuda", compute_type="float16", local_files_only=args.local_files_only)
   segments, info = model.transcribe(audio_path, beam_size=args.beam_size, language="zh",initial_prompt="坦克五百")
   ```

> 2. Have you tried extracting the language probability info for your finetuned model?
>    I am suspecting that somehow during the first 30s which is used to determine the language of the audio, the probability of the Russian is somehow higher than Chinese. It is also very likely that the tokens have been modified during the finetuning.
>    Just to check, does your model (based on whisper v2) transcribe properly when using the huggingface implementation? With and without initial prompt?

       my finetued model (based on whisper v2) transcribe very normally when using the huggingface implementation interface.
       my finetued model (based on whisper v2) transcribe very normally when using fast-whisper implementation interface  without initial prompt, but  my finetued model (based on whisper v2) transcribe incorrectly when using fast-whisper implementation interface  with initial prompt.

> As the initial prompt only preprocesses and converts to tokens in faster-whisper and leaves all the backend computation in ctranslate2. We might need to look into the whisper implementation of ctranslate2. But it is still highly likely that the problem lies in the model rather than the backend.

**Comment by blackpolarz** [comment]
Sorry, that I wasn't able to provide much help and glad that you managed to "adapt" initial_prompt for finetuning. 
Theoretically, initial_prompt is not needed when finetuning. Not sure what is causing the problem.

**Comment by liyaodev** [comment]
initial_prompt="以下是中文普通话句子。" based on this setting, I was able to fix the output to simplified Chinese(简体), and other functions were not found
