### ISSUE TITLE
ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead

### ISSUE THREAD

**Issue by iAladeen** [SYSTRAN/faster-whisper#593]
After i updated the whisperx i am getting this error while transcribing  using large-v3. Anyone else facing same?

`ValueError: Invalid input features shape: expected an input with shape (1, 128, 3000), but got an input with shape (1, 80, 3000) instead`

**Comment by trungkienbkhn** [comment]
Maybe same issue with #582 , please make sure you use the Systran HF model (https://huggingface.co/Systran/faster-whisper-large-v3) and update to the latest version 0.10.0

**Comment by mattiadg** [comment]
I get the same error with the OpenAI model, but only if I quantize to int8. When I don't apply quantization it works fine.

**Comment by hallkass** [comment]
in my case tokenizer.json and preprocessor_config.json were missing in model directory after i converted whisper model to ct2

error dissapeared after i converted like this: 

ct2-transformers-converter --model openai/whisper-tiny --output_dir whisper-tiny-ct2 --copy_files tokenizer.json preprocessor_config.json

**Comment by ChenZheChina** [comment]
In my case it was preprocessor_config.json that was missing.

`ct2-transformers-converter --model ./finetuned --output_dir finetuned.ct2 --copy_files preprocessor_config.json generation_config.json`

This worked for me. The command includes generation_config.json because the tutorial for converting ct2 said so.
