### ISSUE TITLE
Bug with the prompt reset on temp!

### ISSUE THREAD

**Issue by Purfview** [SYSTRAN/faster-whisper#603]
```
Processing segment at 00:52.160
DEBUG: Compression ratio threshold is not met with temperature 0.0 (8.777778 > 2.400000)
DEBUG: Compression ratio threshold is not met with temperature 0.2 (9.307692 > 2.400000)
DEBUG: Log probability threshold is not met with temperature 0.4 (-1.716158 < -1.000000)
DEBUG: Log probability threshold is not met with temperature 0.6 (-2.491989 < -1.000000)
DEBUG: Log probability threshold is not met with temperature 0.8 (-3.483112 < -1.000000)
DEBUG: Log probability threshold is not met with temperature 1.0 (-2.989720 < -1.000000)
[00:52.160 --> 00:54.160]  I'm sorry.
DEBUG: TEMPERATURE at the end of generate_segments(): 0.4
Processing segment at 00:54.160
```

Why at the end of `generate_segments()` temperature is only 0.4?

**Comment by Purfview** [comment]
I've looked at the reference Whisper, I don't see such behavior. It must be the bug.

That can be the source of various hallucinations.

**Comment by Purfview** [comment]
@hoonlight I think it's started to happen after your PR. When model selects a results with not the highest temp when all fallbacks fail, I think it breaks logic behind the prompt resetting.

**Comment by Purfview** [comment]
Fixed:

```
Processing segment at 00:52.160
DEBUG: Compression ratio threshold is not met with temperature 0.0 (8.777778 > 2.400000)
DEBUG: Log probability threshold is not met with temperature 0.2 (-1.855183 < -1.000000)
DEBUG: Log probability threshold is not met with temperature 0.4 (-1.759178 < -1.000000)
DEBUG: Log probability threshold is not met with temperature 0.6 (-1.986997 < -1.000000)
DEBUG: Log probability threshold is not met with temperature 0.8 (-2.949637 < -1.000000)
DEBUG: Log probability threshold is not met with temperature 1.0 (-3.869733 < -1.000000)
[01:02.160 --> 01:12.160]  Oh, my God!
DEBUG: Reset prompt. prompt_reset_on_temperature threshold is met 1.000000 > 0.500000
Processing segment at 01:12.160
```

**Comment by trungkienbkhn** [comment]
@Purfview , hello.
I think the current logic still correct. If all the generated texts do not satisfy the above 3 conditions, model will choose the generated text with the best avg_logprob among the 6 candidates. (In your case, this is -1.759178 with temperature 0.4):
1. compression_ratio <= options.compression_ratio_threshold (2.4)
2. avg_logprob >= options.log_prob_threshold (-1.0)
3. no_speech_prob <= option.no_speech_threshold (0.6)

So when running to the reset_prompt logic, the final temperature should be 0.4 instead of 1.0, because model does not select the generated text with temperature 1.0.
If the current logic causes various hallucinations, could you retry with smaller prompt_reset_on_temperature threshold (for example 0.3 instead 0.5) or set condition_on_previous_text=False?

Can you please re-verify this point. Tks.

**Comment by funboarder13920** [comment]
The issue is that the decoding had to go through different temperatures, hence a prompt reset could have been triggered, but we tempered with the temperature in the result in a previous PR which had an impact on the prompt reset.
It is not because amongst all the unconvincing results we chose the least worst one rather than the last temperature one that we do not want to trigger the prompt reset anymore. 

You can see in the PR when this issue was introduced, and i am pretty sure it was not intended to not reset the prompt anymore.

**Comment by Purfview** [comment]
> @Purfview , hello. I think the current logic still correct. If all the generated texts do not satisfy the above 3 conditions, model will choose the generated text with the best avg_logprob among the 6 candidates (In your case, this is -1.759178 with temperature 0.4):
> 
>     1. compression_ratio <= options.compression_ratio_threshold (2.4)
> 
>     2. avg_logprob >= options.log_prob_threshold (-1.0)
> 
>     3. no_speech_prob <= option.no_speech_threshold (0.6)
> 
> 
> So when running to the reset_prompt logic, the final temperature should be 0.4 instead of 1.0, because model does not select the generated text with temperature 1.0 as the final result to display. According to my understanding, we need to reset prompt for the next tokens if the previous tokens are too random (higher temporature).
> 
> If the current logic causes various hallucinations, could you retry with smaller prompt_reset_on_temperature threshold (for example 0.3 instead 0.5) or set condition_on_previous_text=False?
> 
> Can you please re-verify this point. Tks.

It's not correct, because selected result with `0.4` is not valid for vanilla "prompt_reset_on_temperature" logic.
If selected `0.4` result didn't met "pseudo vad" conditions then it can't be valid.
And that's how vanilla Whisper would work.

> If the current logic causes various hallucinations, could you retry with smaller prompt_reset_on_temperature threshold (for example 0.3 instead 0.5) or set condition_on_previous_text=False?

No, with this logic we deviate from the vanilla logic. To fit in the vanilla logic, in this case we would need to use different  avg_logprob.

**Comment by trungkienbkhn** [comment]
Thanks for your explaination, your PR looks good to me now.
@Purfview Btw, could you please squash your commits ?

**Comment by Purfview** [comment]
> Btw, could you please squash your commits ?

I can't.
This operation can be done when merging by the maintainer.
