### ISSUE TITLE
Does it support converting to ONNX format models？

### ISSUE THREAD

**Issue by dfengpo** [SYSTRAN/faster-whisper#787]
I use C#，
Does it support converting to ONNX format models？
Or how to use C # to call this model？

**Comment by AmgadHasan** [comment]
Instead of converting from faster-whisper format, you can directly convert the pytorch models to onnx format.
For example, if you want to convert `large-v2`, you can use the workflow mentioned in this page on https://huggingface.co/openai/whisper-large-v2

https://huggingface.co/docs/transformers/en/serialization#exporting-a--transformers-model-to-onnx-with-cli

**Comment by lmxin123** [comment]
thank you,I try later

**Comment by ridwan-salau** [comment]
Hey @lmxin123, did you try? How did it go?

**Comment by lmxin123** [comment]
> Hey @lmxin123, did you try? How did it go?

Not yet, I haven't found a way yet
