### ISSUE TITLE
"Thanks for watching" shows up repeatedly

### ISSUE THREAD

**Issue by ENDERFUN2** [SYSTRAN/faster-whisper#826]
So, I have this issue: when there is silence in the recorded audio, whisper, instead of giving out blank string is outputting "Thanks for watching!" or sometimes "Thank you!", but as soon as there is something else than silence it transcribes it 100% perfect. i dunno what causes it, but it's very crucial for me to return blank string, when there's complete silence. Here is my code:
```python
import os
import time

import soundfile
import sounddevice
import numpy

from faster_whisper import WhisperModel


class WhisperTranscriber:
    def __init__(self, model_size="medium", sample_rate=48000):
        self.filename = "C:/Windows/Temp/clara_recording.wav"
        self.data = None
        self.model_size = model_size
        self.sample_rate = sample_rate
        self.model = WhisperModel(model_size, device="cuda", compute_type="float16")

    def record(self, duration, sr):
        data = sounddevice.rec(int(duration * sr), samplerate=sr, channels=1, blocking=True)
        if self.data is None:
            self.data = data
        else:
            self.data = numpy.vstack((self.data, data))
        normalized_data = data / numpy.max(numpy.abs(data))
        return normalized_data

    def is_silent(self, data, threshold):
        rms = numpy.mean(numpy.abs(data))
        return rms > threshold

    def stop_on_silence(self, duration=1.0, sr=48000, threshold=0.15):
        rec = []

        while True:
            data = self.record(duration, sr)
            if self.is_silent(data, threshold):
                break
            rec.extend(data)

        open(self.filename, "w+b")
        soundfile.write(self.filename, self.data, self.sample_rate)

    def transcribe(self):
        self.stop_on_silence()
        file = open(self.filename, "rb")
        segments, info = self.model.transcribe(file, language="en", condition_on_previous_text=False)
        file.close()
        self.data = None
        return ''.join(segment.text for segment in segments)


whisper = WhisperTranscriber()


def get_voice_prompt():
    return whisper.transcribe()


for i in range(0,20):
    print("Started recording")
    print(get_voice_prompt())

```
Also, if you can provide me with a way to feed the audio directly to the AI and not temporarily to file, I wold be so grateful. When I try to pass the recorded data into the model, it crashes with:
```
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 944. GiB for an array with shape (528000, 480001) and data type float32
```

**Comment by trungkienbkhn** [comment]
@ENDERFUN2 , hello. To handle silence in recorded audio, you can try using the `vad_filter` option.
To avoid save audio to temp file, you should pass the audio data as numpy ndarray to FW model. Below is my example:
```python3
import numpy as np
import sounddevice as sd

from faster_whisper import WhisperModel

print("Recording started")
duration = 10
sample_rate = 16000
audio_data = sd.rec(
    int(sample_rate * duration), samplerate=sample_rate, channels=1, dtype=np.float32
)
sd.wait()
audio_data = audio_data.squeeze()
print("Recording stopped")

model = WhisperModel("tiny", device="cpu")
segments, info = model.transcribe(audio_data, word_timestamps=True)
for segment in segments:
    print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
```

**Comment by ENDERFUN2** [comment]
Okay, so vad_filter works perfectly. I don't know why I hadn't found it before...
Also, that sample code from @trungkienbkhn turned out to be a game changer. But, as a curious man, why is squeeze required?It's my first serious project in Python, 'cause all my previous were in Java or C++, therefore I don't really understand it. And why sample rate has to be set to 16000? When I pass the audio file with 48000 sample rate, it transcribes the audio 100% perfect. Would so grateful for explanaition

**Comment by arunman1kandan** [comment]
Hey @ENDERFUN2 ,
Assume you have a box full of Legos and want to construct a spacecraft. To be used, all of the Legos should be loose and in the box.However, occasionally, a smaller box within the larger box may contain the Legos. This extra box is merely there; it contains no Legos.The sounddevice.rec function in this code is analogous to obtaining a Lego box. There could be an additional, empty box included (the extra dimension).It's like opening the large box and removing the smaller, empty one when you use the squeeze feature. It takes out the superfluous box so that all you have to work with is the audio data, or Legos.This is significant because the WhisperModel.transcribe method, which you use to construct the spaceship, is limited to working with loose Legos and not with boxes inside boxes. Squeezing ensures that everything operates as intended and removes the excess box.

This is as how I understood the squeeze works.

**Comment by trungkienbkhn** [comment]
@ENDERFUN2 , FYI, you can see this [comment](https://github.com/openai/whisper/discussions/870#discussioncomment-4743438) to better understand why should use sample_rate=16000. If I use sr=48000 in my example in [here](https://github.com/SYSTRAN/faster-whisper/issues/826#issuecomment-2103713651), obviously it doesn't work.

For why use squeeze(), sd.rec() func returns an array with shape `(duration * sample_rate, 1)` because it records mono audio, resulting in a 2D array with one of the dimensions having size 1. However, FW requires input as a 1D array. So we need use squeeze() to reformat.

**Comment by ENDERFUN2** [comment]
Well, it now makes a lot of sense. Thank you both @trungkienbkhn @arunman1kandan for your service, although abstracting it to Legos wasn't necessary, I just didn't understand ndarrays. Also, after some refactoring I noticed that my code is one big pile of garbage and I should reformat it asap. Your answers gave me an important insight

**Comment by ENDERFUN2** [comment]
Well, it now makes a lot of sense. Thank you both @trungkienbkhn @arunman1kandan for your service, although abstracting it to Legos wasn't necessary, I just didn't understand ndarrays. Also, after some refactoring I noticed that my code is one big pile of garbage and I should reformat it asap. Your answers gave me an important insight
