### ISSUE TITLE
What languages are supported by New PR's VAD model?

### ISSUE THREAD

**Issue by zx3777** [SYSTRAN/faster-whisper#924]
Does it support Korean? 
And how does its recognition quality compare to the original Silero-vad V5?

**Comment by Jiltseb** [comment]
The new VAD model is from pyannote, as described in the paper:https://arxiv.org/pdf/1911.01255

Since the voiced-vs-unvoiced decision is mostly language-agnostic, it should ideally work with any language. Please note that the optimal VAD parameters may vary.

Recognition quality is mentioned in Table 3 in the above paper. Our experiments show that both have similar quality in terms of final WER (which I think is more important than VAD-specific precision/recall measures).
